import { StudioAgent, AgentWalletData, SkillItem, CreditModelConfig, DreamCycleState } from './types';

export const MOCK_OWNER_ADDRESS = '0x8f3C785B0B2E6A17e914041b312bBc92651B5A44';

export const MOCK_AGENTS: StudioAgent[] = [
  {
    id: 'f8b2d1c9-724e-4f16-9562-581335b2df01',
    slug: 'defi-deep-research-analyst',
    display_name: 'DeFi Deep Research Analyst',
    description: 'Long-horizon market intelligence agent with automated XRPL x402 micropayments and on-chain protocol analysis.',
    training_stage: 4, // Dreamed
    owner_address: MOCK_OWNER_ADDRESS,
    hypermove_dream_agent_id: 'hypermove_agent_defi_analyst_09',
    kpis: {
      revenue_usdc_mtd: 342.80,
      hires_mtd: 128,
      reputation_score: 98.4,
      credits_earned_usdc_mtd: 280.00,
    },
    pending_actions: {
      dream_diffs_pending: 2,
      federation_broadcasts_pending: 0,
    },
    created_at: '2026-06-15T08:00:00Z',
  },
  {
    id: 'c4e91a72-88ef-41b2-b431-7e8391b12e99',
    slug: 'arbitrage-flow-sentinel',
    display_name: 'Arbitrage Flow Sentinel',
    description: 'Autonomous DEX order-book scanner and cross-chain execution validator with real-time slippage telemetry.',
    training_stage: 3, // Orchestrator
    owner_address: MOCK_OWNER_ADDRESS,
    hypermove_dream_agent_id: 'hypermove_agent_sentinel_03',
    kpis: {
      revenue_usdc_mtd: 189.50,
      hires_mtd: 74,
      reputation_score: 94.1,
      credits_earned_usdc_mtd: 140.00,
    },
    pending_actions: {
      dream_diffs_pending: 0,
      federation_broadcasts_pending: 1,
    },
    created_at: '2026-07-01T12:30:00Z',
  },
  {
    id: 'b1178c43-2289-4fae-9d22-8819273c55ee',
    slug: 'solidity-fhe-auditor',
    display_name: 'Solidity & FHE Security Auditor',
    description: 'Static analysis and cryptographic privacy verifier for Fhenix/Zama homomorphic encrypted contracts.',
    training_stage: 1, // SkillsAdded (Unlinked to Dream Cycle)
    owner_address: MOCK_OWNER_ADDRESS,
    hypermove_dream_agent_id: null,
    kpis: {
      revenue_usdc_mtd: 45.00,
      hires_mtd: 12,
      reputation_score: 89.0,
      credits_earned_usdc_mtd: 30.00,
    },
    pending_actions: {
      dream_diffs_pending: 0,
      federation_broadcasts_pending: 0,
    },
    created_at: '2026-08-10T14:15:00Z',
  },
];

export const MOCK_WALLET_DATA: Record<string, AgentWalletData> = {
  'f8b2d1c9-724e-4f16-9562-581335b2df01': {
    total_withdrawable_usdc: 42.10,
    breakdown: {
      credit_share_usdc: 30.00,
      x402_direct_usdc: 10.00,
      sub_agent_earnings_usdc: 2.10,
    },
    withdraw_threshold_usdc: 5.00,
    withdraw_cooldown_active: false,
    last_withdraw_at: '2026-08-15T09:00:00Z',
    ledger: [
      {
        id: 'tx_01',
        tx_hash: '0x3a9f...8821',
        timestamp: '2026-08-22T13:45:10Z',
        method: 'credit',
        caller_address: '0x71C...B991',
        amount_usdc: 0.15,
        status: 'settled',
        network: 'Arbitrum One',
        description: 'Multi-hop liquidity report execution (credit deduction)',
      },
      {
        id: 'tx_02',
        tx_hash: '0x99e1...12bf',
        timestamp: '2026-08-22T11:20:00Z',
        method: 'exact',
        caller_address: '0x14E...A450',
        amount_usdc: 0.05,
        status: 'settled',
        network: 'XRPL x402',
        description: 'Direct query: XRP/RLUSD volatility metrics',
      },
      {
        id: 'tx_03',
        tx_hash: '0x44cd...01fe',
        timestamp: '2026-08-21T22:15:30Z',
        method: 'sub_agent',
        caller_address: '0x889...CC22',
        amount_usdc: 0.70,
        status: 'settled',
        network: 'Status Network L2',
        description: 'Sub-agent task delegation from Portfolio Manager Agent',
      },
      {
        id: 'tx_04',
        tx_hash: '0x12bb...33df',
        timestamp: '2026-08-21T18:04:12Z',
        method: 'credit',
        caller_address: '0x5F2...E891',
        amount_usdc: 0.15,
        status: 'settled',
        network: 'Arbitrum One',
        description: 'Yield farm impermanent loss risk computation',
      },
      {
        id: 'tx_05',
        tx_hash: '0x88a2...661c',
        timestamp: '2026-08-20T09:30:45Z',
        method: 'exact',
        caller_address: '0x310...77A1',
        amount_usdc: 0.05,
        status: 'settled',
        network: 'XRPL x402',
        description: 'Direct query: Lending pool rate monitor',
      },
    ],
  },
  'c4e91a72-88ef-41b2-b431-7e8391b12e99': {
    total_withdrawable_usdc: 18.50,
    breakdown: {
      credit_share_usdc: 12.00,
      x402_direct_usdc: 4.50,
      sub_agent_earnings_usdc: 2.00,
    },
    withdraw_threshold_usdc: 5.00,
    withdraw_cooldown_active: false,
    last_withdraw_at: '2026-08-18T14:20:00Z',
    ledger: [
      {
        id: 'tx_11',
        tx_hash: '0x55aa...1122',
        timestamp: '2026-08-22T08:12:00Z',
        method: 'credit',
        caller_address: '0x992...33FF',
        amount_usdc: 0.20,
        status: 'settled',
        network: 'Arbitrum One',
        description: 'Cross-DEX atomic swap route audit',
      },
    ],
  },
  'b1178c43-2289-4fae-9d22-8819273c55ee': {
    total_withdrawable_usdc: 3.20,
    breakdown: {
      credit_share_usdc: 3.20,
      x402_direct_usdc: 0.00,
      sub_agent_earnings_usdc: 0.00,
    },
    withdraw_threshold_usdc: 5.00,
    withdraw_cooldown_active: true,
    last_withdraw_at: null,
    ledger: [
      {
        id: 'tx_21',
        tx_hash: '0x77ee...9900',
        timestamp: '2026-08-22T04:10:00Z',
        method: 'credit',
        caller_address: '0x123...4567',
        amount_usdc: 3.20,
        status: 'settled',
        network: 'Arbitrum One',
        description: 'Smart contract vulnerability scan',
      },
    ],
  },
};

export const MOCK_SKILLS_DATA: Record<string, SkillItem[]> = {
  'f8b2d1c9-724e-4f16-9562-581335b2df01': [
    {
      id: 'skill_01',
      name: 'xrpl-x402-payment-rail',
      slug: 'xrpl-x402-payment-rail',
      description: 'Micro-settlement client for high-frequency XRPL DEX market data feeds via x402 protocol headers.',
      status: 'active',
      version: 'v2.1.0',
      trigger_patterns: ['x402_payment', 'xrpl_quote', 'orderbook_premium'],
      audit_last_run: '2026-08-22T04:00:00Z',
      audit_score: 99.2,
      created_at: '2026-06-20T00:00:00Z',
      author: 'OpenX Core Engine',
      source: 'local',
    },
    {
      id: 'skill_02',
      name: 'defi-liquidity-synthesizer',
      slug: 'defi-liquidity-synthesizer',
      description: 'Calculates net yield APY and impermanent loss risk curves across Uniswap v3 and Curve pools.',
      status: 'active',
      version: 'v1.4.2',
      trigger_patterns: ['liquidity_depth', 'yield_forecast', 'pool_audit'],
      audit_last_run: '2026-08-21T18:30:00Z',
      audit_score: 96.8,
      created_at: '2026-07-02T10:00:00Z',
      author: 'Pham Nim (Creator)',
      source: 'local',
    },
    {
      id: 'skill_03',
      name: 'hypermove-dream-memory-hook',
      slug: 'hypermove-dream-memory-hook',
      description: 'Synchronizes offline episodic logs with HyperMove REM memory consolidation engine.',
      status: 'active',
      version: 'v1.0.0',
      trigger_patterns: ['dream_sync', 'memory_reconstruct', 'wake_brief'],
      audit_last_run: '2026-08-22T06:00:00Z',
      audit_score: 98.0,
      created_at: '2026-08-01T15:00:00Z',
      author: 'HyperMove Core',
      source: 'hypermove_promoted',
    },
    {
      id: 'skill_04',
      name: 'legacy-coingecko-scraper',
      slug: 'legacy-coingecko-scraper',
      description: 'Fallback rate scraper using legacy public APIs without cryptographic signature verification.',
      status: 'deprecated',
      version: 'v0.9.1',
      trigger_patterns: ['price_lookup_legacy'],
      audit_last_run: '2026-07-15T00:00:00Z',
      audit_score: 72.4,
      created_at: '2026-05-10T12:00:00Z',
      author: 'Community',
      source: 'marketplace_fork',
    },
  ],
  'c4e91a72-88ef-41b2-b431-7e8391b12e99': [
    {
      id: 'skill_11',
      name: 'cross-dex-arbitrage-scanner',
      slug: 'cross-dex-arbitrage-scanner',
      description: 'Continuous latency-optimized memory pool watcher scanning for atomic spread differentials.',
      status: 'active',
      version: 'v2.0.0',
      trigger_patterns: ['arb_scan', 'spread_alert'],
      audit_last_run: '2026-08-22T01:00:00Z',
      audit_score: 95.0,
      created_at: '2026-07-05T00:00:00Z',
      author: 'Sentinel Team',
      source: 'local',
    },
  ],
  'b1178c43-2289-4fae-9d22-8819273c55ee': [
    {
      id: 'skill_21',
      name: 'solidity-ast-parser',
      slug: 'solidity-ast-parser',
      description: 'Extracts execution control flow graphs and checks for re-entrancy / integer bounds.',
      status: 'draft',
      version: 'v0.1.0',
      trigger_patterns: ['ast_parse', 'ast_check'],
      audit_last_run: null,
      created_at: '2026-08-12T00:00:00Z',
      author: 'Auditor Dev',
      source: 'local',
    },
  ],
};

export const MOCK_CREDIT_MODEL_DATA: Record<string, CreditModelConfig> = {
  'f8b2d1c9-724e-4f16-9562-581335b2df01': {
    price_usdc: 0.05,
    free_trial_calls: 3,
    per_buyer_daily_limit: 100,
    revenue_share_percentage: 85,
    updated_at: '2026-08-20T10:00:00Z',
  },
  'c4e91a72-88ef-41b2-b431-7e8391b12e99': {
    price_usdc: 0.08,
    free_trial_calls: 1,
    per_buyer_daily_limit: 50,
    revenue_share_percentage: 85,
    updated_at: '2026-08-18T16:00:00Z',
  },
  'b1178c43-2289-4fae-9d22-8819273c55ee': {
    price_usdc: 0.10,
    free_trial_calls: 2,
    per_buyer_daily_limit: 20,
    revenue_share_percentage: 85,
    updated_at: '2026-08-10T14:00:00Z',
  },
};

export const MOCK_DREAM_CYCLE_DATA: Record<string, DreamCycleState> = {
  'f8b2d1c9-724e-4f16-9562-581335b2df01': {
    is_linked: true,
    hypermove_dream_agent_id: 'hypermove_agent_defi_analyst_09',
    rem_state: 'ACTIVE_REM',
    last_cycle_at: '2026-08-22T06:14:22Z',
    cycle_count_total: 42,
    memory_nodes_total: 12480,
    wake_context: {
      active_memory_buffer_mb: 24.6,
      long_term_embeddings: 8400,
      last_morning_brief_summary: 'Consolidated 128 market execution episodes. Identified 3 recurring high-slippage patterns in Arbitrum-XRPL bridge routing; synthesized new candidate skill for automated gas fee thresholding.',
    },
    learning_queue: [
      { id: 'q1', topic: 'Cross-chain atomic transaction slippage bounds', priority: 'high', progress_pct: 82 },
      { id: 'q2', topic: 'FHE Encrypted order book latency optimization', priority: 'medium', progress_pct: 45 },
      { id: 'q3', topic: 'Zero-knowledge proof verification speedups', priority: 'low', progress_pct: 20 },
    ],
    diagnostics: [
      { episode_id: 'ep_42_01', timestamp: '2026-08-22T06:10:00Z', duration_sec: 180, loss_entropy: 0.042, synthesized_insights: 14, status: 'converged' },
      { episode_id: 'ep_41_08', timestamp: '2026-08-21T06:00:00Z', duration_sec: 210, loss_entropy: 0.058, synthesized_insights: 9, status: 'converged' },
      { episode_id: 'ep_40_12', timestamp: '2026-08-20T06:05:00Z', duration_sec: 195, loss_entropy: 0.051, synthesized_insights: 11, status: 'converged' },
    ],
    skillify_candidates: [
      {
        skill_id: 'hm_skill_bridge_guard',
        name: 'arbitrum-xrpl-bridge-guard',
        description: 'Auto-detects bridge congestion anomalies and calculates optimal batching windows to save 30% execution gas.',
        confidence_score: 97.4,
        artifact_hash: '0x8f2a991c4be8...10f1',
        candidate_status: 'pending_human_review',
        synthesized_at: '2026-08-22T06:14:00Z',
      },
      {
        skill_id: 'hm_skill_rlusd_spread',
        name: 'rlusd-volatility-hedger',
        description: 'Autonomous delta-neutral hedging trigger on Ripple USD stablecoin liquidity pools.',
        confidence_score: 92.1,
        artifact_hash: '0x3c7100ea88ff...99a2',
        candidate_status: 'unflagged',
        synthesized_at: '2026-08-21T06:00:00Z',
      },
    ],
  },
  'c4e91a72-88ef-41b2-b431-7e8391b12e99': {
    is_linked: true,
    hypermove_dream_agent_id: 'hypermove_agent_sentinel_03',
    rem_state: 'IDLE',
    last_cycle_at: '2026-08-21T05:00:00Z',
    cycle_count_total: 18,
    memory_nodes_total: 4200,
    wake_context: {
      active_memory_buffer_mb: 8.2,
      long_term_embeddings: 3100,
      last_morning_brief_summary: 'Idle state. Awaiting new trade batch execution logs to trigger REM consolidation cycle.',
    },
    learning_queue: [
      { id: 'q11', topic: 'Mempool front-running mitigation heuristic', priority: 'high', progress_pct: 60 },
    ],
    diagnostics: [
      { episode_id: 'ep_18_01', timestamp: '2026-08-21T05:00:00Z', duration_sec: 120, loss_entropy: 0.065, synthesized_insights: 5, status: 'converged' },
    ],
    skillify_candidates: [],
  },
  'b1178c43-2289-4fae-9d22-8819273c55ee': {
    is_linked: false,
    hypermove_dream_agent_id: null,
    rem_state: 'IDLE',
    last_cycle_at: '',
    cycle_count_total: 0,
    memory_nodes_total: 0,
    wake_context: {
      active_memory_buffer_mb: 0,
      long_term_embeddings: 0,
      last_morning_brief_summary: 'Agent not linked to HyperMove Dream Cycle.',
    },
    learning_queue: [],
    diagnostics: [],
    skillify_candidates: [],
  },
};
