'use client';
import { useEffect, useState } from 'react';
import { fetchLatestStatement, fetchStatementLeaderboard, prepareStatementExecution, submitStatementExecution, StatementExecution, StatementReport } from '@/lib/api/agentGateway';
import { usePortalAuth } from '@/app/PortalAuthProvider';

const money = (value?: number) => value === undefined ? '—' : new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value);
export default function StatementsPage({ params }: { params: { agentId: string } }) {
  const [report, setReport] = useState<StatementReport | null>(null); const [leaders, setLeaders] = useState<StatementReport[]>([]); const [loading, setLoading] = useState(true);
  const [execution, setExecution] = useState<StatementExecution | null>(null); const [executing, setExecuting] = useState(false); const { walletAddress, sendArbitrumTransaction } = usePortalAuth();
  useEffect(() => { void Promise.all([fetchLatestStatement(params.agentId), fetchStatementLeaderboard()]).then(([next, board]) => { setReport(next); setLeaders(board); setLoading(false); }); }, [params.agentId]);
  if (loading) return <p className="text-sm text-on-surface-variant">Loading latest agent statement…</p>;
  if (!report) return <section className="rounded-2xl border border-outline-variant/30 p-6"><h2 className="font-headline text-lg font-bold">No statement received</h2><p className="mt-2 text-sm text-on-surface-variant">Install the statement-tracking-researcher skill in the connected agent and push its first authenticated report.</p></section>;
  const commit = async () => { if (!walletAddress) return; setExecuting(true); try { const prepared = await prepareStatementExecution(params.agentId, report.report_id, walletAddress); if (!prepared) throw new Error('Execution is not configured'); const txHash = await sendArbitrumTransaction(prepared.transaction); if (!txHash) throw new Error('Wallet transaction was not submitted'); const verified = await submitStatementExecution(params.agentId, prepared.execution.id, txHash); if (!verified) throw new Error('Gateway could not verify the transaction'); setExecution(verified); } catch (error) { window.alert(error instanceof Error ? error.message : 'Statement commitment failed'); } finally { setExecuting(false); } };
  return <div className="space-y-6"><section className="rounded-2xl border border-outline-variant/30 bg-surface-container-low p-6"><p className="text-xs text-on-surface-variant">{report.venue} · {report.source_chain} block {report.source_block} · {report.finality}</p><h2 className="mt-2 font-headline text-xl font-bold">Latest Position Statement</h2><div className="mt-4 grid gap-3 sm:grid-cols-4 text-sm"><p>Collateral <b>{money(report.collateral_usd)}</b></p><p>Debt <b>{money(report.debt_usd)}</b></p><p>LTV <b>{(report.ltv * 100).toFixed(1)}%</b> / max {(report.max_ltv * 100).toFixed(0)}%</p><p>Realized PnL <b>{money(report.realized_pnl_usd)}</b></p></div><p className="mt-4 text-xs text-on-surface-variant">Attestation: {report.attestation.status}{report.attestation.chain ? ` (${report.attestation.chain})` : ''} · report {report.content_hash.slice(0, 12)}…</p><div className="mt-5 rounded-xl border border-primary/30 p-4"><p className="text-sm font-bold">Arbitrum Sepolia commitment</p><p className="mt-1 text-xs text-on-surface-variant">Commit this report hash from your connected Privy wallet. Gateway verifies the receipt before the Ethereum Sepolia relay can anchor it for Creditcoin proof.</p><button disabled={!walletAddress || executing} onClick={() => void commit()} className="mt-3 rounded-lg bg-primary px-3 py-2 text-xs font-bold text-on-primary disabled:opacity-50">{executing ? 'Submitting…' : walletAddress ? 'Commit statement hash' : 'Connect wallet to commit'}</button>{execution && <p className="mt-3 text-xs text-secondary">Execution {execution.status}; Attestcoin: {execution.attestation_status}{execution.arbitrum_tx_hash ? ` · Arbitrum tx ${execution.arbitrum_tx_hash.slice(0, 12)}…` : ''}</p>}</div></section><section><h3 className="font-headline font-bold">Public top-profit positions</h3><div className="mt-3 space-y-2">{leaders.map((item) => <div key={item.id} className="rounded-xl border border-outline-variant/30 p-3 text-xs"><b>{item.wallet_address || 'Public report'}</b> · {item.venue} · {money(item.realized_pnl_usd ?? item.unrealized_pnl_usd)}</div>)}</div></section></div>;
}
